services:
  python:
    build: .
    tty: true
    privileged: true
    volumes:
      - "$PWD:/workspace"
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    command:
      - sh
      - -c
      - |
        nvidia-smi
        date
        sh
